version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: smp-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: shadow-monarchs-path-dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - smp-network

volumes:
  mongodb_data:
    driver: local

networks:
  smp-network:
    driver: bridge
